---
- name: "NodeSource installation"
  become: true
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: Run "apt-get update" 
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes
    
- name: "npm version"
  shell: npm -version

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present
    

- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy files"
  copy:
    src: "files/index.js"
    dest: ~/web
    backup: true

- name: "start server"
  shell: pm2 start ~/web/index.js -f

