# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "Command to print workflow ID"
    parameters:
      id:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps: 
    - run: echo << parameters.id >>

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm run lint


  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm run test
        
  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm audit
        
workflows:
  # Name the workflow "hello_and_world"
  version: 2
  npm workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

Each job should have some common elements. 
For example, before doing anything that works with code, 
you will need to checkout. You may also have to install any 
dependencies needed to run the code or complete some task. 

