# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "Command to print workflow ID"
    parameters:
      id:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps: 
    - run: echo << parameters.id >>

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
working_directory: /tmp
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - print_pipeline_id:
          id:
      - run: mkdir -p workspace
      - run: cd workspace
      - run: sudo echo "You are working"> workspace/output.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - output.txt
      - run: cat workspace/output.txt

  print_output_file:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - attach_workspace:
          at: workspace
      - run: cat workspace/output.txt
      - run: 
          name: read_error
          command: echo "Failed to read the output file"
          when: on_fail
        
workflows:
  # Name the workflow "hello_and_world"
  version: 2
  save_and_output_using_workspace:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
